on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: crates-lsp
          # extension-path: extensions/${{ extension-name }}
          push-to: appelgriebsch/zed-extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
